let prompts = [
  [
    "Human",
    "Elf",
    "Dwarf",
    "Orc",
    "Dragon",
    "Giant",
    "Goblin",
    "Kobold",
    "Merfolk",
    "Nymph",
    "Satyr",
    "Troll",
    "Vampire",
    "Lizardfolk",
    "Catfolk",
    "Ghost",
    "Fairy",
    "Gryphon/Griffin",
    "Gremlin",
    "Sylph",
    "Sphinx",
    "Centaur",
    "Demon",
    "Darkelf",
    "Gnome",
    "Ent",
    "Skeleton",
    "Werebeast",
    "Mimic",
    "Golem",
    "Extraterrestrial",
    "Android",
    "Angel",
    "Hobbit",
    "Chimaera",
    "Ghoul",
    "Imp",
    "Phoenix",
    "Unicorn",
    "Banshee",
    "Dryad",
    "Naga",
    "Mutant",
    "Slimefolk",
    "Dinosaur",
    "Minotaur",
    "Undead",
    "Harpy",
    "Siren",
    "Valkyrie",
    "God/Godess",
    "Mech",
    "Artifical Intelligence",
    "Construct",
  ],
  [
    "Warrior",
    "Archer",
    "Rogue",
    "Mage",
    "Sorcerer",
    "Wizard",
    "Knight",
    "Thief",
    "Merchant",
    "Paladin",
    "Farmer",
    "Politician",
    "Miner",
    "Barbarian",
    "Fisher",
    "Pirate",
    "Monk",
    "Priest",
    "Blacksmith",
    "Bartender",
    "Bard",
    "Healer",
    "Nurse",
    "Pilot",
    "Mechanic",
    "Dancer",
    "Professor",
    "Scientist",
    "Singer",
    "Butcher",
    "Baker",
    "Druid",
    "Shaman",
    "Ranger",
    "Hacker",
    "Bounty Hunter",
    "Cultist",
    "Assassin",
    "Spy",
    "Scoundrel",
    "Smuggler",
    "Jedi",
    "Sith",
    "Officer",
    "Gunslinger",
    "Sharpshooter",
    "Thug",
    "Alchemist",
    "Exile",
    "Spacer",
    "Investigator",
    "Detective",
    "Explorer",
    "Adventurer",
    "Cybernetic/Augmented",
    "Apprentice",
  ],
  [
    "Cat",
    "Dog",
    "Chicken",
    "Duck",
    "Aardvark",
    "Albatross",
    "Alligator",
    "Alpaca",
    "Ant",
    "Anteater",
    "Antelope",
    "Ape",
    "Armadillo",
    "Donkey",
    "Monkey",
    "Badger",
    "Fish",
    "Bat",
    "Bear",
    "Beaver",
    "Bee",
    "Songbird",
    "Bison",
    "Boar",
    "Bobcat",
    "Budgie",
    "Butterfly",
    "Camel",
    "Capybara",
    "Caracal",
    "Caterpillar",
    "Cow",
    "Cheetah",
    "Chimpanzee",
    "Chinchilla",
    "Cobra",
    "Cockroach",
    "Cougar",
    "Coyote",
    "Crab",
    "Cricket",
    "Crane",
    "Crocodile",
    "Crow",
    "Cuckoo",
    "Deer",
    "Dolphin",
    "Pidgeon",
    "Dragonfly",
    "Eagle",
    "Eel",
    "Elephant",
    "Seal",
    "Manatee",
    "Elk",
    "Emu",
    "Falcon",
    "Ferret",
    "Flamingo",
    "Fly",
    "Fox",
    "Frog",
    "Gecko",
    "Panda",
    "Giraffe",
    "Mosquito",
    "Goose",
    "Gorilla",
    "Grasshopper",
    "Guinea Pig",
    "Gull",
    "Hamster",
    "Hedgehog",
    "Hippopotamus",
    "Hornet",
    "Horse",
    "Hummingbird",
    "Hyena",
    "Ibex",
    "Iguana",
    "Jackal",
    "Jaguar",
    "Jellyfish",
    "Kangaroo",
    "Koala",
    "Lizard",
    "Ladybug",
    "Lemur",
    "Leopard",
    "Lion",
    "Llama",
    "Lobster",
    "Lynx",
    "Parrot",
    "Mammoth",
    "Marmoset",
    "Meerkat",
    "Mole",
    "Mongoose",
    "Moose",
    "Mouse",
    "Narwhal",
    "Newt",
    "Ocelot",
    "Octopus",
    "Okapi",
    "Opossum",
    "Ostrich",
    "Otter",
    "Owl",
    "Oyster",
    "Panther",
    "Red Panda",
    "Peacock",
    "Penguin",
    "Pheasant",
    "Pig",
    "Porcupine",
    "Prairie Dog",
    "Rabbit",
    "Racoon",
    "Sheep",
    "Rat",
    "Reindeer",
    "Rhinoceros",
    "Salamander",
    "Salmon",
    "Sand Dollar",
    "Sea Lion",
    "Seahorse",
    "Shark",
    "Skunk",
    "Sloth",
    "Snail/Slug",
    "Snake",
    "Spider",
    "Squid",
    "Squirrel",
    "Swan",
    "Tapir",
    "Termite",
    "Tiger",
    "Toad",
    "Toucan",
    "Turkey",
    "Turtle",
    "Vulture",
    "Viper",
    "Wallaby",
    "Walrus",
    "Wasp",
    "Buffalo",
    "Weasel",
    "Whale",
    "Wolf",
    "Wombat",
    "Worm",
    "Bird of Prey",
    "Zebra",
    "Zooplankton",
    "Kiwi",
    "Shrimp",
    "Sea Slug",
    "Puffin",
    "Beetle",
    "Insect",
    "Mantis",
    "Scorpion",
    "Moth",
    "Centipede",
  ],
  [
    "Tree",
    "Grass",
    "Bush",
    "Herb",
    "Alder",
    "Almond",
    "Aloe Vera",
    "Amaranth",
    "Ambrosia",
    "Apple",
    "Apricot",
    "Sycamore",
    "Bamboo",
    "Fern",
    "Banana",
    "Baobab",
    "Bay Leaf",
    "Bean",
    "Beech",
    "Crane Flower",
    "Birch",
    "Cress",
    "Blackberry",
    "Blueberry",
    "Bluebell",
    "Broadleaf",
    "Chestnut",
    "Cabbage",
    "Broccoli",
    "Walnut",
    "Carrot",
    "Root",
    "Cherry",
    "Chrysanthemum",
    "Cinnamon",
    "Clove",
    "Clover",
    "Coconut",
    "Coffee Bean",
    "Coneflower",
    "Cornflower",
    "Corydalis",
    "Cotton",
    "Cucumber",
    "Daisy",
    "Nettle",
    "Thistle",
    "Durian",
    "Orchid",
    "Elderberry",
    "Lupine",
    "Eucalyptus",
    "Huckleberry",
    "Moss",
    "Fennel",
    "Forget-Me-Not",
    "Fig",
    "Flax",
    "Foxglove",
    "Garlic",
    "Gilliflower",
    "Golden Rain Flower",
    "Grapefruit",
    "Vine",
    "Hellebore",
    "Hemp",
    "Cannabis",
    "Holly",
    "Leek",
    "Hydrangea",
    "Acacia",
    "Ivy",
    "Jasmine Flower",
    "Juniper",
    "Kudzu Plant",
    "Asparagus",
    "Palm",
    "Magnolia",
    "Lavender",
    "Lemon",
    "Lily",
    "Lily of the Valley",
    "Lettuce",
    "Lilac",
    "Sunflower",
    "Bleeding Heart Flower",
    "Maize/Corn",
    "Mango",
    "Maple",
    "Morel",
    "Mahogany",
    "Mulberry",
    "Fuchsia",
    "Cactus",
    "Nightshade",
    "Oak",
    "Olive",
    "Onion",
    "Orange",
    "Willow",
    "Parsley",
    "Parsnip",
    "Pea",
    "Peach",
    "Peanut",
    "Pear",
    "Pine",
    "Pineapple",
    "Pistachio",
    "Plantain",
    "Poplar",
    "Poppy",
    "Potato",
    "Primrose",
    "Canola/Rapeseed",
    "Raspberry",
    "Rhubarb",
    "Rice",
    "Rose",
    "Rosemary",
    "Rye",
    "Saffron",
    "Strawberry",
    "Sugarcane",
    "Sweet Potato",
    "Tansy",
    "Tea",
    "Thyme",
    "Tobacco",
    "Tomato",
    "Touch-Me-Not",
    "Trillium",
    "Tuber",
    "Tulip",
    "Violet Flower",
    "Voodoo Lily",
    "Weeds",
    "Wheat",
    "Honeysuckle",
    "Hops",
    "Yarrow",
    "Yam",
    "Basil",
    "Chili",
    "Elm",
    "Grape",
    "Pumpkin",
    "Venus Flytrap",
    "Windflower",
    "Fir",
    "Kiwi Fruit",
    "Snapdragon",
    "Beet",
    "Dragonfruit",
    "Cedar",
    "Bonsai",
    "Chamomile",
    "Tree Fern",
    "Cosmo",
    "Hyacinth",
    "Mum Flower",
    "Pansy",
    "Carnation",
    "Rafflesia",
    "Dandelion",
  ],
];

function handleClickOne() {
  let randomOne = Math.floor(Math.random() * prompts[0].length);
  let promptOne = document.querySelector(".prompt-1");
  promptOne.classList.add("placeholder");
  promptOne.innerHTML = prompts[0][randomOne];
}

function handleClickThree() {
  let randomOne = Math.floor(Math.random() * prompts[0].length);
  let randomTwo = Math.floor(Math.random() * prompts[1].length);
  let randomFour = Math.floor(Math.random() * prompts[3].length);
  let promptTwo = document.querySelector(".prompt-2");
  promptTwo.classList.add("placeholder");
  let promptThree = document.querySelector(".prompt-3");
  promptThree.classList.add("placeholder");
  let promptFour = document.querySelector(".prompt-4");
  promptFour.classList.add("placeholder");
  promptTwo.innerHTML = prompts[0][randomOne];
  promptThree.innerHTML = prompts[1][randomTwo];
  promptFour.innerHTML = prompts[3][randomFour];
}

function handleClickFive() {
  let randomOne = Math.floor(Math.random() * prompts[0].length);
  let randomTwo = Math.floor(Math.random() * prompts[1].length);
  let randomThree = Math.floor(Math.random() * prompts[2].length);
  let randomFour = Math.floor(Math.random() * prompts[3].length);
  let randomFive = Math.floor(Math.random() * prompts[0].length);
  let promptOne = document.querySelector(".prompt-1");
  promptOne.classList.add("placeholder");
  let promptTwo = document.querySelector(".prompt-2");
  promptTwo.classList.add("placeholder");
  let promptThree = document.querySelector(".prompt-3");
  promptThree.classList.add("placeholder");
  let promptFour = document.querySelector(".prompt-4");
  promptFour.classList.add("placeholder");
  let promptFive = document.querySelector(".prompt-5");
  promptFive.classList.add("placeholder");
  promptOne.innerHTML = prompts[0][randomOne];
  promptTwo.innerHTML = prompts[1][randomTwo];
  promptThree.innerHTML = prompts[2][randomThree];
  promptFour.innerHTML = prompts[3][randomFour];
  promptFive.innerHTML = prompts[0][randomFive];
}

function handleRadio() {
  let checkOne = document.getElementById("inlineRadio1");
  let checkThree = document.getElementById("inlineRadio2");
  let checkFive = document.getElementById("inlineRadio3");
  if (checkOne.checked == true) {
    let clickOne = document.querySelector(".go-button");
    clickOne.addEventListener("click", handleClickOne);
  } else if (checkThree.checked == true) {
    let clickThree = document.querySelector(".go-button");
    clickThree.addEventListener("click", handleClickThree);
  } else if (checkFive.checked == true) {
    let clickFive = document.querySelector(".go-button");
    clickFive.addEventListener("click", handleClickFive);
  }
}

let radioCheckOne = document.querySelector("#inlineRadio1");
radioCheckOne.addEventListener("change", handleRadio);
let radioCheckThree = document.querySelector("#inlineRadio2");
radioCheckThree.addEventListener("change", handleRadio);
let radioCheckFive = document.querySelector("#inlineRadio3");
radioCheckFive.addEventListener("change", handleRadio);
